import { NextResponse } from "next/server";

import { getSessionUser } from "@/lib/auth/guards";
import { storage } from "@/server/adapters/storage";
import { canStudentReadResume } from "@/server/services/student-service";

/**
 * Streams a resume file to its owning student. Permission is enforced
 * here, BEFORE we touch storage — even if the storage layer leaks bytes,
 * the gate is in front of it. Companies / admins get broader access in
 * later tasks via a role-aware permission rule.
 *
 * The `key` is URL-encoded, so we decode once. Storage keys generated by
 * `LocalFsStorageAdapter` look like `resumes/<uuid>.<ext>`.
 */
export async function GET(
  _req: Request,
  ctx: { params: Promise<{ key: string }> },
) {
  const { key: encoded } = await ctx.params;
  const storageKey = decodeURIComponent(encoded);

  const user = await getSessionUser();
  if (!user) {
    return NextResponse.json({ error: "unauthenticated" }, { status: 401 });
  }

  // V1 rule for Task 6: only the owning student. Tasks 12+ extend this
  // to companies viewing applicants tied to their own postings.
  if (user.role !== "STUDENT") {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }
  const allowed = await canStudentReadResume(user.id, storageKey);
  if (!allowed) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  let result;
  try {
    result = await storage.read(storageKey);
  } catch {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }

  if (result.kind === "redirect") {
    return NextResponse.redirect(result.url);
  }

  return new NextResponse(new Uint8Array(result.bytes), {
    status: 200,
    headers: {
      "Content-Type": result.contentType,
      "Content-Disposition": `inline; filename="${sanitizeFilename(result.filename)}"`,
      "Cache-Control": "private, no-store",
    },
  });
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^A-Za-z0-9._-]/g, "_");
}
